name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ compiler
        run: sudo apt-get install g++

      - name: Compile program
        run: g++ -o Eval eval2.cpp

      - name: Run program
        run: ./name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ compiler
        run: sudo apt-get install g++

      - name: Compile program
        run: g++ -o eval1_even ques2.cpp

      - name: Run program
        run: ./eval1_even
